server:
  port: 5003

# datasoure默认使用JDBC
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: aliyun-qihui
    url: jdbc:mysql://101.132.174.159:3306/pig?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false

zipkin:
  collector:
    rabbitmq:
      host: 101.132.174.159
      username: admin
      password: admin
      queue: zipkin
  storage:
    type: mysql
